server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/movie?useSSL=false&amp&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: dbuser
    password: dbpassword

#pagehelper 分页插件
page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

